[package]
name = "sf15to18"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "15to18"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.9", features = ["cargo"] }
